name: Generate snake animation

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate contribution snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=000000,2d2d2d,595959,9e9e9e,ffffff&color_dots=f2f2f2,cfcfcf,9e9e9e,595959,000000
            dist/github-contribution-grid-snake-dark.svg?color_snake=000000,2d2d2d,595959,9e9e9e,ffffff&color_dots=161616,2d2d2d,595959,9e9e9e,ffffff&color_dot_border=2d2d2d

      - name: Publish to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
